### ISSUE TITLE
view渲染传递数据对象

### ISSUE THREAD

**Issue by xinglie** [thx/magix#20]
现在应用的方案：

``` html
<div mx-view="path/to/view?args1=1&args2=2"></div>
```

这种和`iframe`通过`src`链接传递数据是一样的，遗憾的是这种只能传递简单的字符串数据，如果想传递一个数据对象则需要动态渲染，如下

``` js
render:function(){
    this.owner.mountVframe('id','path/to/view',{
          a1:1,
          a2:2
    });
}
```

在使用时多有不便。

如果想像别的框架那样可以直接通过`html`里面的标识传递复杂的数据对象，那就需要约定写法
### 约定数据位置

我们在项目中使用时并不强制开发者怎么把数据挂到`view`对象上，属于自由开放式的。如果要完成上述功能，则需要我们把数据统一放到某个地方，比如`view.data`对象上，这样`magix`在渲染`view`时才知道去哪个对象上拿数据
### 约定读取格式

是通过之前的类似`url`的方式传递？对参数特殊化？比如`mx-view="path/to/view?args1={data.a1}"`
还是额外再节点上添加？如`<div mx-data-args1="data.a1" mx-viw="..."></div>`

这块需要定一下

**Comment by xinglie** [comment]
暂定规则为 
```html
<div mx-data="{key1:data.key1,key2:data.key2,width:100,str:'str'}" mx-view="path/to/view?width=50"></div>
```

mx-data是类似json对象，key无须用双引号引起来。当mx-data中与path的search中存在相同key，示例中的width,mx-data中的会覆盖掉search中的值。

当mx-data中能识别为字符串及数字时，magix会做类型转换，其它值则从view上读取数据

**Comment by purplebamboo** [comment]
示例中的width,mx-data中的会覆盖掉search中的值。 这个我觉得并不是很有必要，这种隐性的转换，反而容易造成新手的困扰。

**Comment by xinglie** [comment]
@purplebamboo 
因为最初设计是可以通过path传递简单参数的，那现在新增加了mx-data，会出现上述示例的情况，这种情况如何处理`width`？还是说使用了mx-data就不要再用path传递参数了？

**Comment by purplebamboo** [comment]
另外 我们是不是参考 react的  props的实现方式，往子view传递数据，不要这种｛｝对象的形式。而是作为一个属性。然后所有的属性可以在子view的this.props对象上获得。

```
<div key1="$key1" key2="ddad"  mx-view="path/to/view?width=50"></div>
```
比如上面的，我们设置了多个属性，如果是$开头的，那么我们就认为是需要从父级获取data里面的为key1的数据给子view。如果没有那么就是普通字符串。

所有的属性提取出来放到props可以跟data区分开来，本来就是两个东西。不应该相互影响。

**Comment by xinglie** [comment]
@purplebamboo 这种还是需要约定一下吧，难道通过node.attributes获取所有属性再一个个分析？
可以挂到props上，不知道用起来是不是方便，这块我是想向以往的版本靠拢的，因为已经习惯在
```js
init:function(extra){

}
```
通过init接收数据了，接收到的数据用户可以放在任何地方。
如果是props上,在使用时再转换到data上？
```js
init:function(){
    this.data.key1=this.props.key1;
}
```
这样么？

**Comment by purplebamboo** [comment]
@xinglie  嗯嗯   可以选择性的使用。 我也就建议哈，具体的还要讨论下。的确得照顾下以前的习惯。

**Comment by gongeek** [comment]
我喜欢直接从extra拿，跟手动mount保持统一更好。

**Comment by xinglie** [comment]
@gongeek 可以，那用`mx-init`

**Comment by xinglie** [comment]
```html
<div mx-view="path/to/view" mx-init="{key:data,int:20,str:'string'}"></div>
```

**Comment by xinglie** [comment]
确定内置基于underscore模板改造后的模板。不再讨论
