### ISSUE TITLE
双向绑定与view之间的细节

### ISSUE THREAD

**Issue by xinglie** [thx/magix#22]
考虑这样的场景：

``` html
<div mx-view="<%=view%>"></div>
```
1. 初始化时view无值，不渲染
2. 应用过程中数据改变，比如从有值到无值，则界面上销毁view及其vframe。

**Comment by xinglie** [comment]
目前内置的updater因为是根据数据变化的key来更新界面的，因此对于这个问题比较容易解

**Comment by xinglie** [comment]
对于pat或vue需要在数据改变时，通过更新的节点，识别更新的节点是view且改变的数据会引起view变化，则调用magix提供的vframe的方法进行渲染或销毁

**Comment by youwenda** [comment]
mark一下：

1. vue监听到变更view path后，销毁vframe去进行重新渲染的时机是异步，而本来要销毁的view可能因为监听地址栏参数的变化导致render重新调用的方法是同步的，会导致render再次调用；

2.通过 mx-init传递数据 mx-init=“{a:data.a,b:data.b}”   数据变化反映不到path的变化上，因此本应该重新mount view的操作失败

**Comment by xinglie** [comment]
@youwenda 第1点只有在异步渲染的情况下有问题，不过这也于magix的隐藏细节有关，按流程上来讲，当path变化时，开发者应该先销毁之前渲染的view，然后再合适的时候渲染新view，之不过在我们平常的使用中，把销毁旧view，渲染新view这2步合成一步了，如果严格按先销毁旧的，再渲染新的，也不会有问题。

**Comment by xinglie** [comment]
确定内置基于underscore模板改造后的模板。不再讨论
