### ISSUE TITLE
更改vframe node节点属性造成多次渲染view失效

### ISSUE THREAD

**Issue by youwenda** [thx/magix#45]
https://github.com/thx/magix/blob/7847c3f3253bcd25d9157a716554e503120f0fe1/src/tmpl/vframe.js#L492

对于需要多次渲染vframe的情况
`<div mx-view="view1"></div><div mx-view="view2"></div>`，`<div>`钩子节点并不会被销毁，挂在dom上的$m属性依然存在，因此第二次重新调用`mountZone收集 `mx-view` 节点时无法收集到。

这里暂时解决方法为：(不了解layerFrame目的)

![image](https://user-images.githubusercontent.com/2204911/33409012-40ee5e7c-d5b4-11e7-97c6-42dbbfb47aaa.png)

**Comment by xinglie** [comment]
### 修复方案
在vframe移除时，同时移除节点上的标识
