### ISSUE TITLE
Wrap Render 方法应该返回render的结果

### ISSUE THREAD

**Issue by youwenda** [thx/magix#46]
https://github.com/thx/magix/blob/master/src/tmpl/view.js#L59
magix 1.0 magix 1.1 都做了。但是magix1.2 也没有返回值。

在重构过程中，发现业务代码有类似的写法，依赖`render`方法的返回值。

```
this.render().then()
```

**Comment by xinglie** [comment]
具体的业务场景是怎样的？我看下具体的使用场景
> 从1.2移除render的返回值是因为render方法受到销毁的控制，view在销毁后，再调用render方法是不会执行开发者提供的真实render方法，也就无法得到正确的返回值。这个过程并不是透明的，所以干脆去掉返回值，后续应该也不会添加

**Comment by youwenda** [comment]
在重构过程中，有业务同学基于magix1.0写出如下代码：

```
render: function() {
     return promise;
},
otherMethods: function() {
     this.render().then(function() {
     })
}
```
因为Magix1.2和Magix3 封装的render不再返回render方法原有值。因此替换Magix3之后出现问题。
这种情况很少，目前只发现一例。但根据尽量不改变业务代码的前提下，目前在Magix3的patch代码中对于封装render方法依然返回值。暂时解决了该问题。

看来render删除返回值是有目的的，因此我还是去改业务源码好了。
