### ISSUE TITLE
环境搭建 设置jquery处代码出错了

### ISSUE THREAD

**Issue by wudi3** [thx/magix#48]
http://thx.github.io/magix/#!/tutorial?s=set-up

// magix为了同时支持jquery和zepto, 在依赖的时候，使用了中性名称$，  
             // 代表jquery或者zepto，具体是使用jquery还是zepto  
             // 需要在这里对使用的框架进行配置才能被正确解析  
             define(',['jquery'],function($){  
                 return $  
             })  

貌似应该写成这样：

 define('$', ['jquery'], function($) {
		        return $;
	        });

**Comment by xinglie** [comment]
@wudi3  是的，这里代码乱掉了，回头我更新下这块的代码
