### ISSUE TITLE
安装tnpm时，无法安装

### ISSUE THREAD

**Issue by jiahongsheng** [thx/magix#57]
npm install --registry=https://registry.npm.alibaba-inc.com -g tnpm
我通过这个文档https://thx.github.io/magix-cli-book/#/quickStart
安装[Magix 套件](https://thx.github.io/magix-cli-book/)，在安装tnpm时，无法访问到https://registry.npm.alibaba-inc.com ，这个地址是不维护了吗

**Comment by xinglie** [comment]
@jiahongsheng 使用https://github.com/thx/thx-cli这个工具进行开发，https://thx.github.io/magix/
